[package]
name = "typed-fuse-core"
version = "0.6.0"
description = "Backend-neutral, node-tracking core for building FUSE filesystems"
repository = "https://github.com/vgough/typed-fuse"
authors = ["Valient Gough <vgough@arg0.net>"]
license = "MIT"
readme = "../README.md"
keywords = ["fuse", "filesystem", "fs"]
categories = ["filesystem"]
edition = "2024"

[dependencies]
libc = "0.2"
