[package]
name = "typed-fuse"
version = "0.5.1"
description = "High-level, safe Rust wrapper for building FUSE 3 filesystems"
repository = "https://github.com/vgough/typed-fuse"
authors = ["Valient Gough <vgough@arg0.net>"]
license = "MIT"
readme = "README.md"
keywords = ["fuse", "filesystem", "fs", "bindings"]
categories = ["filesystem"]
edition = "2024"

[dependencies]
libfuse-sys = { path = "../libfuse-sys", default-features = false, features = ["fuse_lowlevel", "fuse_312"] }
typed-fuse-core = { path = "../typed-fuse-core" }
libc = "0.2"
log = "0.4"

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
anyhow = "1"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = { version = "0.39", default-features = false, features = ["system"] }
tempfile = "3"

[[bench]]
name = "filesystem"
harness = false
