name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:

jobs:
  build-ubuntu-typed-fuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install libfuse3-dev
        run: sudo apt-get install -y libfuse3-dev

      - name: Build
        run: cargo build --features fuse_35 --examples --verbose

      - name: Test
        run: cargo test --workspace --verbose


  build-macos-11:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install osxfuse
        run: brew install osxfuse

      - name: Build
        run: cargo build --verbose
